---
  - name : This is my first playbook
    hosts : test
    tasks:
      
      - name : Installing htppd server
        apt :
          name : nginx
          state : present

      - name : Installing docker and its packages
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present


      - name: Add Docker repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu focal stable
          state: present

      - name: update and install docker
        apt:
          name: docker-ce
          update_cache: yes
          state: latest

      - name : We are going to create a user in dev and test servers
        user :
          name: ubuntu
          groups: docker
          append: true
          state: present

